<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CanonicalPreference
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanonicalPreference extends EntityRepository
{
}
