{tmplinclude file="header.phtml"}

{if isset( $session->domain ) && $session->domain }
    {assign var=domain value=$session->domain}
{/if}

<div class="page-content" >

    <div class="page-header" >

        <div style="float: right; margin-top: -10px;">
            <div class="btn-toolbar">
                    <span class="btn-group">
                    {if $ima}   
                        <a class="btn have-tooltip-below" id="ima" title="Hide Mailbox Canonical" href="{genUrl controller='canonical' action='list' ima=0}{if isset( $domain ) && $domain}/did/{$domain->getId()}{/if}" >
            	            <i class="icon-eye-open"></i>
                        </a>
                    {else}
                        <a class="btn have-tooltip-below" id="ima" title="Show Mailbox Canonical" href="{genUrl controller='canonical' action='list' ima=1}{if isset( $domain ) && $domain}/did/{$domain->getId()}{/if}" >
                            <i class="icon-eye-close"></i>
                        </a>
                    {/if}
        	        <a class="btn have-tooltip-below" id="add_canonical" title="Add Canonical" href="{genUrl controller='canonical' action='add'}{if isset( $domain ) && $domain}/did/{$domain->getId()}{/if}">

            	        <i class="icon-plus"></i>
        	        </a>
            	</span>
        	</div>

    	</div>

        <h1>
            Canonical {if isset( $domain ) && $domain }<small> for {$domain->getDomain()} {if $domain->getMaxCanonical() != 0}({$domain->getCanonicalCount()}/{$domain->getMaxCanonical()}){/if}</small>
                <a class="btn have-tooltip-below" id="show_all_canonical" title="Show All" href="{genUrl controller='canonical' action='list' unset=1}{if $ima}/ima/1{/if}"><i class="icon-remove-circle"></i></a>
            {/if}
        </h1>
    </div>

{OSS_Message}

<br/>

<table id="list_table" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Address</th>
            <th>Domain</th>
            <th width="55">Active</th>
            <th>Sender</th>
            <th width="60"></th>
        </tr>
    </thead>
    <tbody>
    {foreach $canonical as $sender_canonical}
        <tr id="canonical_{$sender_canonical.id}">
            <td>{$sender_canonical.address}</td>
            <td>{$sender_canonical.domain}</td>
            <td>
                <div id="throb-toggle-active-{$sender_canonical.id}" style="float: right;"></div>
                <span id="toggle-active-{$sender_canonical.id}" onclick="toggleActive( 'toggle-active-{$sender_canonical.id}', {$sender_canonical.id} );" class="btn btn-mini {if $sender_canonical.active}btn-success{else}btn-danger{/if}">{$sender_canonical.active|yesno}</span>
            </td>
            <td>
                <div id="canonical-sender-{$sender_canonical.id}" {if strlen( $sender_canonical.sender ) > 50 } class="have-tooltip-long" title="{$sender_canonical.sender|regex_replace:"/[,]/":", "}"{/if}>
                {$sender_canonical.sender|shorten:50}
                </div>
            </td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-mini have-tooltip" id="edit_canonical_{$sender_canonical.id}" title="Edit" href="{genUrl controller='canonical' action='edit' caid=$sender_canonical.id}">
                        <i class="icon-pencil"></i>
                    </a>
                    {if isset( $canonical_actions ) }
                        {assign var=oid value=$sender_canonical.id}
                        {foreach $canonical_actions as $action}
                            {if isset( $action.menu ) }
                                {assign var="action_list_menu" value=$action}
                            {else}
                                <{$action.tagName} {foreach $action as $attrib => $value}{if !in_array( $attrib, [ "tagName", "child"] )}{$attrib}="{$value|replace:'%id%':$oid}" {/if}{/foreach}>
                                {if !is_array( $action.child ) }
                                    {$action.child}
                                {else}
                                    <{$action.child.tagName} {foreach $action.child as $attrib => $value}{if $attrib != "tagName"}{$attrib}="{$value}" {/if}{/foreach} {if $action.child.tagName != "img"}></{$action.child.tagName}>{else}/>{/if}
                                {/if}
                                </{$action.tagName}>
                            {/if}
                        {/foreach}
                    {/if}
                    <a class="btn btn-mini have-tooltip" id="delete-canonical-{$sender_canonical.id}" title="Delete" href="{genUrl controller='canonical' action='delete' caid=$sender_canonical.id}">
                        <i class="icon-trash"></i>
                    </a>
                    {if isset( $action_list_menu)}
                        {assign var="action" value=$action_list_menu}
                        <{$action.tagName} {foreach $action as $attrib => $value}{if !in_array( $attrib, [ "tagName", "child", "menu" ] )}{$attrib}="{$value|replace:'%id%':$oid}" {/if}{/foreach}>
                        {if !is_array( $action.child ) }
                            {$action.child}
                        {else}
                            <{$action.child.tagName} {foreach $action.child as $attrib => $value}{if $attrib != "tagName"}{$attrib}="{$value}" {/if}{/foreach} {if $action.child.tagName != "img"}></{$action.child.tagName}>{else}/>{/if}
                        {/if}
                        <span class="caret"></span>
                        </{$action.tagName}>
                        <ul class="dropdown-menu pull-right">
                        {foreach $action.menu as $item}
                            <li><a {if isset( $item.id)}id="{$item.id|replace:'%id%':$oid}" {/if}href="{$item.url|replace:'%id%':$oid}">{$item.text}</a></li>
                        {/foreach}
                        </ul>
                    {/if}
                </div>
            </td>
        </tr>
    {/foreach}
    </tbody>
</table>

<br />
<br />
<br />

<script type="text/javascript">{tmplinclude file='canonical/js/list.js'}</script>

<div id="purge_dialog" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
        <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
        Are you sure you want to delete this canonical?
    </div>
    <div id="pdfooter" class="modal-footer">
        <a class="btn btn-danger" id="purge_dialog_delete" href="#">Delete</a>
        <button id="purge_dialog_cancel" class="btn">Cancel</button>
    </div>
</div>

</div>
{tmplinclude file="footer.phtml"}
